DROP DATABASE IF EXISTS phonebookdb;
CREATE DATABASE IF NOT EXISTS phonebookdb
  DEFAULT CHARACTER SET utf8;
USE phonebookdb;

CREATE TABLE users
(
  id INT(10) unsigned PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) DEFAULT '' NOT NULL,
  secondname VARCHAR(50) DEFAULT '' NOT NULL,
  surname VARCHAR(50) DEFAULT '' NOT NULL
);

CREATE TABLE phones
(
  id INT(10) unsigned PRIMARY KEY NOT NULL,
  phonenumber VARCHAR(9) DEFAULT '' NOT NULL,
  phonetype ENUM('HOME', 'MOBILE', 'UNKNOWN') DEFAULT 'UNKNOWN' NOT NULL,
  comment VARCHAR(9) DEFAULT '' NOT NULL,
  FOREIGN KEY (id) REFERENCES users (id)
);
